"use client";

import { useEffect, useState } from "react";
import { persistClientLanguage, resolveClientLanguage } from "@/lib/language-preference";
import { normalizeUiLanguage, type UiLanguage } from "@/lib/ui-i18n";

export const mobileEase = [0.23, 1, 0.32, 1] as const;

export const mobileCopy = {
  es: {
    login: "Login",
    enterOff: "Entrar a OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Todo parece avanzar.",
    heroEmphasis: "Pero algo dentro sigue apagado.",
    heroSubtitle: "OFF nace para una generación que está construyendo éxito mientras intenta no perderse a sí misma.",
    recent: "Lecturas recientes",
    chapters: "Capítulos",
    aboutTitle: "No es motivación. Es claridad.",
    aboutCopy: "Una editorial psicológica para volver a pensar, sentir y construir con dirección.",
    impact: "Impacto",
    readers: "Lectores alcanzados",
    choseSelf: "Personas que decidieron elegirse",
    stories: "Historias compartidas",
    rebuilding: "Jóvenes reconstruyendo dirección",
    receive: "Recibe OFF",
    subscribeTitle: "Sin ruido. Solo ideas que te regresan dirección.",
    lounge: "The Member Lounge",
    loungeCopy: "Una sala privada para leer sin prisa, encontrar dirección y volver a ideas que merecen quedarse contigo.",
    continueReading: "Continuar leyendo",
    memberSince: "Miembro desde",
    timeInvested: "Tiempo invertido en OFF",
    offId: "OFF ID",
    membershipBadge: "Insignia OFF Member",
    currentReading: "Lectura actual",
    noCurrentReading: "Tu próxima lectura aparecerá aquí.",
    noReadingsYet: "Sin lecturas aún",
    noBadgesYet: "Sin insignias aún",
    progressTimeline: "Progreso del miembro",
    editorialCollections: "COLECCIONES EDITORIALES",
    library: "Biblioteca",
    mySelfTitle: "Conociendo mi modo ON",
    mySelfKicker: "Mi Yo",
    profileTitle: "Tu recorrido OFF",
    profileKicker: "Perfil",
    moreTitle: "Conoce Más",
    moreKicker: "OFF",
    behindOff: "Detrás de OFF",
    behindOffCopy: "Detrás de OFF hay alguien que también está en construcción.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    community: "Community",
    language: "Idioma",
    exit: "Salir",
    articlesCompleted: "Artículos completados",
    badges: "Insignias",
    noArticles: "Cuando publiques capítulos, aparecerán aquí con datos reales.",
    volume: "Volumen",
    more: "Más",
    mobileLoungeNavigation: "Navegación del Lounge",
    search: "Buscar",
    searchInOff: "Buscar en OFF...",
    searchError: "No pudimos completar la búsqueda.",
    searching: "Buscando...",
    clear: "Limpiar búsqueda",
    explore: "Explorar",
    noResults: "No encontramos nada con esa búsqueda.",
    noResultsHelp: "Prueba con otra palabra o explora una categoría.",
    gallery: "Galería",
    visualArchive: "Archivo visual",
    galleryIntro: "Imágenes y señales visuales para mirar lo que también cuesta explicar.",
    galleryFilters: "Filtros de Galería",
    all: "Todos",
    loadMore: "Cargar más",
    loading: "Cargando...",
    close: "Cerrar",
    previous: "Anterior",
    next: "Siguiente",
    back: "Volver",
    galleryEmpty: "La Galería todavía no tiene publicaciones en esta categoría.",
    galleryError: "No pudimos cargar la Galería.",
    galleryImageAlt: "Imagen editorial de OFF",
    galleryVideoAlt: "Video editorial de OFF",
    music: "Música",
    playMusic: "Reproducir música",
    pauseMusic: "Pausar música",
    like: "Me gusta",
    share: "Compartir",
    shareOtherApp: "Compartir en otra app",
    copyLink: "Copiar enlace",
    linkCopied: "Enlace copiado.",
    shareWithMember: "Compartir con un miembro",
    memberSearchPlaceholder: "Nombre u OFF ID",
    sharedWith: "Compartido con",
    comments: "Comentarios",
    writeComment: "Escribe un comentario...",
    publishComment: "Publicar comentario",
    deleteComment: "Eliminar comentario",
    interactionError: "No pudimos completar la acción.",
    publishContent: "Publicar contenido",
    editContent: "Editar contenido",
    preview: "Vista previa",
    uploadFile: "Subir archivo",
    replaceFile: "Reemplazar archivo",
    edit: "Editar",
    zoom: "Zoom",
    reset: "Restablecer",
    dragToFrame: "Arrastra directamente el contenido para cambiar el encuadre.",
    category: "Categoría",
    internalTitle: "Título interno",
    optional: "Opcional",
    postCaption: "Pie de publicación",
    postCaptionPlaceholder: "Escribe el pie de esta publicación...",
    altTextLabel: "Texto alternativo",
    altTextPlaceholder: "Describe el contenido visual para accesibilidad.",
    videoPoster: "Poster del video",
    uploadPoster: "Subir poster",
    addMusic: "Agregar música",
    replace: "Reemplazar",
    uploadAudio: "Subir audio",
    songTitle: "Nombre de la canción",
    artist: "Artista",
    removeMusic: "Quitar música",
    saveDraft: "Guardar draft",
    publish: "Publicar",
    frameRecommendation: "Frame editorial 3:4 · 1080 × 1440 recomendado",
    chatWelcome: "Hola, soy tu asistente OFF. Estoy aquí para ayudarte a ordenar ideas, entender lo que estás sintiendo y convertirlo en claridad accionable.",
    chatPending: "Ordenando la idea...",
    chatPlaceholder: "Escribe lo que quieres ordenar...",
    chatMessage: "Mensaje para el asistente OFF",
    send: "Enviar",
    backToLounge: "Volver al Lounge",
  },
  en: {
    login: "Login",
    enterOff: "Enter OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Everything seems to move forward.",
    heroEmphasis: "But something inside still feels off.",
    heroSubtitle: "OFF is for a generation building success while trying not to lose itself.",
    recent: "Recent readings",
    chapters: "Chapters",
    aboutTitle: "It is not motivation. It is clarity.",
    aboutCopy: "A psychological editorial space to think, feel and build with direction again.",
    impact: "Impact",
    readers: "Readers reached",
    choseSelf: "People who chose themselves",
    stories: "Stories shared",
    rebuilding: "Young people rebuilding direction",
    receive: "Receive OFF",
    subscribeTitle: "No noise. Only ideas that bring direction back.",
    lounge: "The Member Lounge",
    loungeCopy: "A private room to read slowly, find direction and return to ideas worth keeping.",
    continueReading: "Continue reading",
    memberSince: "Member since",
    timeInvested: "Time invested in OFF",
    offId: "OFF ID",
    membershipBadge: "OFF Member badge",
    currentReading: "Current reading",
    noCurrentReading: "Your next reading will appear here.",
    noReadingsYet: "No readings yet",
    noBadgesYet: "No badges yet",
    progressTimeline: "Member progress",
    editorialCollections: "EDITORIAL COLLECTIONS",
    library: "Library",
    mySelfTitle: "Knowing my ON mode",
    mySelfKicker: "My Self",
    profileTitle: "Your OFF journey",
    profileKicker: "Profile",
    moreTitle: "Learn More",
    moreKicker: "OFF",
    behindOff: "Behind OFF",
    behindOffCopy: "Behind OFF is someone who is still building herself, too.",
    chatTitle: "OFF Chat",
    chatKicker: "Chat",
    community: "Community",
    language: "Language",
    exit: "Exit",
    articlesCompleted: "Articles completed",
    badges: "Badges",
    noArticles: "When chapters are published, they will appear here with real data.",
    volume: "Volume",
    more: "More",
    mobileLoungeNavigation: "Lounge navigation",
    search: "Search",
    searchInOff: "Search OFF...",
    searchError: "We could not complete the search.",
    searching: "Searching...",
    clear: "Clear search",
    explore: "Explore",
    noResults: "We could not find anything for that search.",
    noResultsHelp: "Try another word or explore a category.",
    gallery: "Gallery",
    visualArchive: "Visual archive",
    galleryIntro: "Images and visual signals for looking at what is also difficult to explain.",
    galleryFilters: "Gallery filters",
    all: "All",
    loadMore: "Load more",
    loading: "Loading...",
    close: "Close",
    previous: "Previous",
    next: "Next",
    back: "Back",
    galleryEmpty: "The Gallery does not have posts in this category yet.",
    galleryError: "We could not load the Gallery.",
    galleryImageAlt: "OFF editorial image",
    galleryVideoAlt: "OFF editorial video",
    music: "Music",
    playMusic: "Play music",
    pauseMusic: "Pause music",
    like: "Like",
    share: "Share",
    shareOtherApp: "Share to another app",
    copyLink: "Copy link",
    linkCopied: "Link copied.",
    shareWithMember: "Share with a member",
    memberSearchPlaceholder: "Name or OFF ID",
    sharedWith: "Shared with",
    comments: "Comments",
    writeComment: "Write a comment...",
    publishComment: "Publish comment",
    deleteComment: "Delete comment",
    interactionError: "We could not complete that action.",
    publishContent: "Publish content",
    editContent: "Edit content",
    preview: "Preview",
    uploadFile: "Upload file",
    replaceFile: "Replace file",
    edit: "Edit",
    zoom: "Zoom",
    reset: "Reset",
    dragToFrame: "Drag the content directly to change the framing.",
    category: "Category",
    internalTitle: "Internal title",
    optional: "Optional",
    postCaption: "Post caption",
    postCaptionPlaceholder: "Write the caption for this post...",
    altTextLabel: "Alt text",
    altTextPlaceholder: "Describe the visual content for accessibility.",
    videoPoster: "Video poster",
    uploadPoster: "Upload poster",
    addMusic: "Add music",
    replace: "Replace",
    uploadAudio: "Upload audio",
    songTitle: "Song title",
    artist: "Artist",
    removeMusic: "Remove music",
    saveDraft: "Save draft",
    publish: "Publish",
    frameRecommendation: "3:4 editorial frame · 1080 × 1440 recommended",
    chatWelcome: "Hi, I am your OFF assistant. I am here to help you organize ideas, understand what you feel and turn it into actionable clarity.",
    chatPending: "Organizing the idea...",
    chatPlaceholder: "Write what you want to organize...",
    chatMessage: "Message for the OFF assistant",
    send: "Send",
    backToLounge: "Back to the Lounge",
  },
  it: {
    login: "Login",
    enterOff: "Entra in OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Tutto sembra andare avanti.",
    heroEmphasis: "Ma qualcosa dentro resta spento.",
    heroSubtitle: "OFF nasce per una generazione che costruisce successo senza volersi perdere.",
    recent: "Letture recenti",
    chapters: "Capitoli",
    aboutTitle: "Non è motivazione. È chiarezza.",
    aboutCopy: "Uno spazio editoriale psicologico per pensare, sentire e costruire con direzione.",
    impact: "Impatto",
    readers: "Lettori raggiunti",
    choseSelf: "Persone che hanno scelto se stesse",
    stories: "Storie condivise",
    rebuilding: "Giovani che ricostruiscono direzione",
    receive: "Ricevi OFF",
    subscribeTitle: "Niente rumore. Solo idee che riportano direzione.",
    lounge: "The Member Lounge",
    loungeCopy: "Una sala privata per leggere senza fretta, trovare direzione e tornare a idee che meritano di restare.",
    continueReading: "Continua a leggere",
    memberSince: "Membro da",
    timeInvested: "Tempo investito in OFF",
    offId: "OFF ID",
    membershipBadge: "Badge OFF Member",
    currentReading: "Lettura attuale",
    noCurrentReading: "La tua prossima lettura apparirà qui.",
    noReadingsYet: "Nessuna lettura",
    noBadgesYet: "Nessun badge",
    progressTimeline: "Progressi del membro",
    editorialCollections: "COLLEZIONI EDITORIALI",
    library: "Biblioteca",
    mySelfTitle: "Conoscere il mio modo ON",
    mySelfKicker: "Il mio io",
    profileTitle: "Il tuo percorso OFF",
    profileKicker: "Profilo",
    moreTitle: "Scopri di più",
    moreKicker: "OFF",
    behindOff: "Dietro OFF",
    behindOffCopy: "Dietro OFF c'è qualcuno che sta ancora costruendo anche se stessa.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    community: "Community",
    language: "Lingua",
    exit: "Esci",
    articlesCompleted: "Articoli completati",
    badges: "Badge",
    noArticles: "Quando pubblicherai capitoli, appariranno qui con dati reali.",
    volume: "Volume",
    more: "Altro",
    mobileLoungeNavigation: "Navigazione Lounge",
    search: "Cerca",
    searchInOff: "Cerca in OFF...",
    searchError: "Non è stato possibile completare la ricerca.",
    searching: "Ricerca in corso...",
    clear: "Cancella ricerca",
    explore: "Esplora",
    noResults: "Non abbiamo trovato risultati.",
    noResultsHelp: "Prova un'altra parola o esplora una categoria.",
    gallery: "Galleria",
    visualArchive: "Archivio visivo",
    galleryIntro: "Immagini e segnali visivi per guardare ciò che è difficile spiegare.",
    galleryFilters: "Filtri Galleria",
    all: "Tutti",
    loadMore: "Carica altro",
    loading: "Caricamento...",
    close: "Chiudi",
    previous: "Precedente",
    next: "Successivo",
    back: "Indietro",
    galleryEmpty: "La Galleria non ha ancora contenuti in questa categoria.",
    galleryError: "Non è stato possibile caricare la Galleria.",
    galleryImageAlt: "Immagine editoriale OFF",
    galleryVideoAlt: "Video editoriale OFF",
    music: "Musica",
    playMusic: "Riproduci musica",
    pauseMusic: "Pausa musica",
    like: "Mi piace",
    share: "Condividi",
    shareOtherApp: "Condividi in un'altra app",
    copyLink: "Copia link",
    linkCopied: "Link copiato.",
    shareWithMember: "Condividi con un membro",
    memberSearchPlaceholder: "Nome o OFF ID",
    sharedWith: "Condiviso con",
    comments: "Commenti",
    writeComment: "Scrivi un commento...",
    publishComment: "Pubblica commento",
    deleteComment: "Elimina commento",
    interactionError: "Non è stato possibile completare l'azione.",
    publishContent: "Pubblica contenuto",
    editContent: "Modifica contenuto",
    preview: "Anteprima",
    uploadFile: "Carica file",
    replaceFile: "Sostituisci file",
    edit: "Modifica",
    zoom: "Zoom",
    reset: "Ripristina",
    dragToFrame: "Trascina il contenuto per modificare l'inquadratura.",
    category: "Categoria",
    internalTitle: "Titolo interno",
    optional: "Opzionale",
    postCaption: "Didascalia",
    postCaptionPlaceholder: "Scrivi la didascalia di questa pubblicazione...",
    altTextLabel: "Testo alternativo",
    altTextPlaceholder: "Descrivi il contenuto visivo per l'accessibilità.",
    videoPoster: "Poster del video",
    uploadPoster: "Carica poster",
    addMusic: "Aggiungi musica",
    replace: "Sostituisci",
    uploadAudio: "Carica audio",
    songTitle: "Titolo del brano",
    artist: "Artista",
    removeMusic: "Rimuovi musica",
    saveDraft: "Salva bozza",
    publish: "Pubblica",
    frameRecommendation: "Frame editoriale 3:4 · 1080 × 1440 consigliato",
    chatWelcome: "Ciao, sono il tuo assistente OFF. Ti aiuto a ordinare le idee, capire ciò che senti e trasformarlo in chiarezza concreta.",
    chatPending: "Sto ordinando l'idea...",
    chatPlaceholder: "Scrivi ciò che vuoi mettere in ordine...",
    chatMessage: "Messaggio per l'assistente OFF",
    send: "Invia",
    backToLounge: "Torna al Lounge",
  },
  pt: {
    login: "Login",
    enterOff: "Entrar no OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Tudo parece avançar.",
    heroEmphasis: "Mas algo dentro segue apagado.",
    heroSubtitle: "OFF nasce para uma geração construindo sucesso sem querer se perder.",
    recent: "Leituras recentes",
    chapters: "Capítulos",
    aboutTitle: "Não é motivação. É clareza.",
    aboutCopy: "Um espaço editorial psicológico para voltar a pensar, sentir e construir com direção.",
    impact: "Impacto",
    readers: "Leitores alcançados",
    choseSelf: "Pessoas que escolheram a si mesmas",
    stories: "Histórias compartilhadas",
    rebuilding: "Jovens reconstruindo direção",
    receive: "Receba OFF",
    subscribeTitle: "Sem ruído. Só ideias que devolvem direção.",
    lounge: "The Member Lounge",
    loungeCopy: "Uma sala privada para ler sem pressa, encontrar direção e voltar a ideias que merecem ficar.",
    continueReading: "Continuar lendo",
    memberSince: "Membro desde",
    timeInvested: "Tempo investido na OFF",
    offId: "OFF ID",
    membershipBadge: "Insígnia OFF Member",
    currentReading: "Leitura atual",
    noCurrentReading: "Sua próxima leitura aparecerá aqui.",
    noReadingsYet: "Sem leituras ainda",
    noBadgesYet: "Sem insígnias ainda",
    progressTimeline: "Progresso do membro",
    editorialCollections: "COLEÇÕES EDITORIAIS",
    library: "Biblioteca",
    mySelfTitle: "Conhecendo meu modo ON",
    mySelfKicker: "Meu Eu",
    profileTitle: "Sua jornada OFF",
    profileKicker: "Perfil",
    moreTitle: "Conheça Mais",
    moreKicker: "OFF",
    behindOff: "Por trás da OFF",
    behindOffCopy: "Por trás da OFF há alguém que também continua se construindo.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    community: "Community",
    language: "Idioma",
    exit: "Sair",
    articlesCompleted: "Artigos concluídos",
    badges: "Insígnias",
    noArticles: "Quando capítulos forem publicados, aparecerão aqui com dados reais.",
    volume: "Volume",
    more: "Mais",
    mobileLoungeNavigation: "Navegação do Lounge",
    search: "Buscar",
    searchInOff: "Buscar na OFF...",
    searchError: "Não foi possível concluir a busca.",
    searching: "Buscando...",
    clear: "Limpar busca",
    explore: "Explorar",
    noResults: "Não encontramos nada nessa busca.",
    noResultsHelp: "Tente outra palavra ou explore uma categoria.",
    gallery: "Galeria",
    visualArchive: "Arquivo visual",
    galleryIntro: "Imagens e sinais visuais para olhar o que também é difícil explicar.",
    galleryFilters: "Filtros da Galeria",
    all: "Todos",
    loadMore: "Carregar mais",
    loading: "Carregando...",
    close: "Fechar",
    previous: "Anterior",
    next: "Próximo",
    back: "Voltar",
    galleryEmpty: "A Galeria ainda não tem publicações nesta categoria.",
    galleryError: "Não foi possível carregar a Galeria.",
    galleryImageAlt: "Imagem editorial da OFF",
    galleryVideoAlt: "Vídeo editorial da OFF",
    music: "Música",
    playMusic: "Reproduzir música",
    pauseMusic: "Pausar música",
    like: "Curtir",
    share: "Compartilhar",
    shareOtherApp: "Compartilhar em outro app",
    copyLink: "Copiar link",
    linkCopied: "Link copiado.",
    shareWithMember: "Compartilhar com um membro",
    memberSearchPlaceholder: "Nome ou OFF ID",
    sharedWith: "Compartilhado com",
    comments: "Comentários",
    writeComment: "Escreva um comentário...",
    publishComment: "Publicar comentário",
    deleteComment: "Excluir comentário",
    interactionError: "Não foi possível concluir a ação.",
    publishContent: "Publicar conteúdo",
    editContent: "Editar conteúdo",
    preview: "Prévia",
    uploadFile: "Enviar arquivo",
    replaceFile: "Substituir arquivo",
    edit: "Editar",
    zoom: "Zoom",
    reset: "Restaurar",
    dragToFrame: "Arraste o conteúdo para alterar o enquadramento.",
    category: "Categoria",
    internalTitle: "Título interno",
    optional: "Opcional",
    postCaption: "Legenda da publicação",
    postCaptionPlaceholder: "Escreva a legenda desta publicação...",
    altTextLabel: "Texto alternativo",
    altTextPlaceholder: "Descreva o conteúdo visual para acessibilidade.",
    videoPoster: "Poster do vídeo",
    uploadPoster: "Enviar poster",
    addMusic: "Adicionar música",
    replace: "Substituir",
    uploadAudio: "Enviar áudio",
    songTitle: "Nome da música",
    artist: "Artista",
    removeMusic: "Remover música",
    saveDraft: "Salvar rascunho",
    publish: "Publicar",
    frameRecommendation: "Frame editorial 3:4 · 1080 × 1440 recomendado",
    chatWelcome: "Olá, sou seu assistente OFF. Estou aqui para ajudar a organizar ideias, entender o que você sente e transformar isso em clareza prática.",
    chatPending: "Organizando a ideia...",
    chatPlaceholder: "Escreva o que você quer organizar...",
    chatMessage: "Mensagem para o assistente OFF",
    send: "Enviar",
    backToLounge: "Voltar ao Lounge",
  },
} as const;

export function useMobileCopy(initialLanguage?: string | null) {
  const [language, setLanguage] = useState<UiLanguage>(() => normalizeUiLanguage(initialLanguage ?? null));

  useEffect(() => {
    const sync = (value?: string) => setLanguage(value ? normalizeUiLanguage(value) : resolveClientLanguage(initialLanguage));
    sync();
    persistClientLanguage(resolveClientLanguage(initialLanguage), false);
    const listener = (event: Event) => sync((event as CustomEvent<string>).detail);
    const storageListener = () => sync();
    window.addEventListener("off-language-change", listener);
    window.addEventListener("storage", storageListener);
    return () => {
      window.removeEventListener("off-language-change", listener);
      window.removeEventListener("storage", storageListener);
    };
  }, [initialLanguage]);

  return { language, copy: mobileCopy[language] };
}
