"use client";

import { useEffect, useState } from "react";
import { persistClientLanguage, resolveClientLanguage } from "@/lib/language-preference";
import { normalizeUiLanguage, type UiLanguage } from "@/lib/ui-i18n";

export const mobileEase = [0.23, 1, 0.32, 1] as const;

export const mobileCopy = {
  es: {
    login: "Login",
    enterOff: "Entrar a OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Todo parece avanzar.",
    heroEmphasis: "Pero algo dentro sigue apagado.",
    heroSubtitle: "OFF nace para una generación que está construyendo éxito mientras intenta no perderse a sí misma.",
    recent: "Lecturas recientes",
    chapters: "Capítulos",
    aboutTitle: "No es motivación. Es claridad.",
    aboutCopy: "Una editorial psicológica para volver a pensar, sentir y construir con dirección.",
    impact: "Impacto",
    readers: "Lectores alcanzados",
    choseSelf: "Personas que decidieron elegirse",
    stories: "Historias compartidas",
    rebuilding: "Jóvenes reconstruyendo dirección",
    receive: "Recibe OFF",
    subscribeTitle: "Sin ruido. Solo ideas que te regresan dirección.",
    lounge: "The Member Lounge",
    loungeCopy: "Una sala privada para leer sin prisa, encontrar dirección y volver a ideas que merecen quedarse contigo.",
    continueReading: "Continuar leyendo",
    memberSince: "Miembro desde",
    timeInvested: "Tiempo invertido en OFF",
    offId: "OFF ID",
    membershipBadge: "Insignia OFF Member",
    currentReading: "Lectura actual",
    noCurrentReading: "Tu próxima lectura aparecerá aquí.",
    noReadingsYet: "Sin lecturas aún",
    noBadgesYet: "Sin insignias aún",
    progressTimeline: "Progreso del miembro",
    editorialCollections: "COLECCIONES EDITORIALES",
    library: "Biblioteca",
    mySelfTitle: "Conociendo mi modo ON",
    mySelfKicker: "Mi Yo",
    profileTitle: "Tu recorrido OFF",
    profileKicker: "Perfil",
    moreTitle: "Conoce Más",
    moreKicker: "OFF",
    behindOff: "Detrás de OFF",
    behindOffCopy: "Detrás de OFF hay alguien que también está en construcción.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    language: "Idioma",
    exit: "Salir",
    articlesCompleted: "Artículos completados",
    badges: "Insignias",
    noArticles: "Cuando publiques capítulos, aparecerán aquí con datos reales.",
    volume: "Volumen",
    more: "Más",
    mobileLoungeNavigation: "Navegación del Lounge",
    chatWelcome: "Hola, soy tu asistente OFF. Estoy aquí para ayudarte a ordenar ideas, entender lo que estás sintiendo y convertirlo en claridad accionable.",
    chatPending: "Ordenando la idea...",
    chatPlaceholder: "Escribe lo que quieres ordenar...",
    chatMessage: "Mensaje para el asistente OFF",
    send: "Enviar",
    backToLounge: "Volver al Lounge",
  },
  en: {
    login: "Login",
    enterOff: "Enter OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Everything seems to move forward.",
    heroEmphasis: "But something inside still feels off.",
    heroSubtitle: "OFF is for a generation building success while trying not to lose itself.",
    recent: "Recent readings",
    chapters: "Chapters",
    aboutTitle: "It is not motivation. It is clarity.",
    aboutCopy: "A psychological editorial space to think, feel and build with direction again.",
    impact: "Impact",
    readers: "Readers reached",
    choseSelf: "People who chose themselves",
    stories: "Stories shared",
    rebuilding: "Young people rebuilding direction",
    receive: "Receive OFF",
    subscribeTitle: "No noise. Only ideas that bring direction back.",
    lounge: "The Member Lounge",
    loungeCopy: "A private room to read slowly, find direction and return to ideas worth keeping.",
    continueReading: "Continue reading",
    memberSince: "Member since",
    timeInvested: "Time invested in OFF",
    offId: "OFF ID",
    membershipBadge: "OFF Member badge",
    currentReading: "Current reading",
    noCurrentReading: "Your next reading will appear here.",
    noReadingsYet: "No readings yet",
    noBadgesYet: "No badges yet",
    progressTimeline: "Member progress",
    editorialCollections: "EDITORIAL COLLECTIONS",
    library: "Library",
    mySelfTitle: "Knowing my ON mode",
    mySelfKicker: "My Self",
    profileTitle: "Your OFF journey",
    profileKicker: "Profile",
    moreTitle: "Learn More",
    moreKicker: "OFF",
    behindOff: "Behind OFF",
    behindOffCopy: "Behind OFF is someone who is still building herself, too.",
    chatTitle: "OFF Chat",
    chatKicker: "Chat",
    language: "Language",
    exit: "Exit",
    articlesCompleted: "Articles completed",
    badges: "Badges",
    noArticles: "When chapters are published, they will appear here with real data.",
    volume: "Volume",
    more: "More",
    mobileLoungeNavigation: "Lounge navigation",
    chatWelcome: "Hi, I am your OFF assistant. I am here to help you organize ideas, understand what you feel and turn it into actionable clarity.",
    chatPending: "Organizing the idea...",
    chatPlaceholder: "Write what you want to organize...",
    chatMessage: "Message for the OFF assistant",
    send: "Send",
    backToLounge: "Back to the Lounge",
  },
  it: {
    login: "Login",
    enterOff: "Entra in OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Tutto sembra andare avanti.",
    heroEmphasis: "Ma qualcosa dentro resta spento.",
    heroSubtitle: "OFF nasce per una generazione che costruisce successo senza volersi perdere.",
    recent: "Letture recenti",
    chapters: "Capitoli",
    aboutTitle: "Non è motivazione. È chiarezza.",
    aboutCopy: "Uno spazio editoriale psicologico per pensare, sentire e costruire con direzione.",
    impact: "Impatto",
    readers: "Lettori raggiunti",
    choseSelf: "Persone che hanno scelto se stesse",
    stories: "Storie condivise",
    rebuilding: "Giovani che ricostruiscono direzione",
    receive: "Ricevi OFF",
    subscribeTitle: "Niente rumore. Solo idee che riportano direzione.",
    lounge: "The Member Lounge",
    loungeCopy: "Una sala privata per leggere senza fretta, trovare direzione e tornare a idee che meritano di restare.",
    continueReading: "Continua a leggere",
    memberSince: "Membro da",
    timeInvested: "Tempo investito in OFF",
    offId: "OFF ID",
    membershipBadge: "Badge OFF Member",
    currentReading: "Lettura attuale",
    noCurrentReading: "La tua prossima lettura apparirà qui.",
    noReadingsYet: "Nessuna lettura",
    noBadgesYet: "Nessun badge",
    progressTimeline: "Progressi del membro",
    editorialCollections: "COLLEZIONI EDITORIALI",
    library: "Biblioteca",
    mySelfTitle: "Conoscere il mio modo ON",
    mySelfKicker: "Il mio io",
    profileTitle: "Il tuo percorso OFF",
    profileKicker: "Profilo",
    moreTitle: "Scopri di più",
    moreKicker: "OFF",
    behindOff: "Dietro OFF",
    behindOffCopy: "Dietro OFF c'è qualcuno che sta ancora costruendo anche se stessa.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    language: "Lingua",
    exit: "Esci",
    articlesCompleted: "Articoli completati",
    badges: "Badge",
    noArticles: "Quando pubblicherai capitoli, appariranno qui con dati reali.",
    volume: "Volume",
    more: "Altro",
    mobileLoungeNavigation: "Navigazione Lounge",
    chatWelcome: "Ciao, sono il tuo assistente OFF. Ti aiuto a ordinare le idee, capire ciò che senti e trasformarlo in chiarezza concreta.",
    chatPending: "Sto ordinando l'idea...",
    chatPlaceholder: "Scrivi ciò che vuoi mettere in ordine...",
    chatMessage: "Messaggio per l'assistente OFF",
    send: "Invia",
    backToLounge: "Torna al Lounge",
  },
  pt: {
    login: "Login",
    enterOff: "Entrar no OFF",
    homeEyebrow: "EDITORIAL OFF by MAIA",
    heroTitle: "Tudo parece avançar.",
    heroEmphasis: "Mas algo dentro segue apagado.",
    heroSubtitle: "OFF nasce para uma geração construindo sucesso sem querer se perder.",
    recent: "Leituras recentes",
    chapters: "Capítulos",
    aboutTitle: "Não é motivação. É clareza.",
    aboutCopy: "Um espaço editorial psicológico para voltar a pensar, sentir e construir com direção.",
    impact: "Impacto",
    readers: "Leitores alcançados",
    choseSelf: "Pessoas que escolheram a si mesmas",
    stories: "Histórias compartilhadas",
    rebuilding: "Jovens reconstruindo direção",
    receive: "Receba OFF",
    subscribeTitle: "Sem ruído. Só ideias que devolvem direção.",
    lounge: "The Member Lounge",
    loungeCopy: "Uma sala privada para ler sem pressa, encontrar direção e voltar a ideias que merecem ficar.",
    continueReading: "Continuar lendo",
    memberSince: "Membro desde",
    timeInvested: "Tempo investido na OFF",
    offId: "OFF ID",
    membershipBadge: "Insígnia OFF Member",
    currentReading: "Leitura atual",
    noCurrentReading: "Sua próxima leitura aparecerá aqui.",
    noReadingsYet: "Sem leituras ainda",
    noBadgesYet: "Sem insígnias ainda",
    progressTimeline: "Progresso do membro",
    editorialCollections: "COLEÇÕES EDITORIAIS",
    library: "Biblioteca",
    mySelfTitle: "Conhecendo meu modo ON",
    mySelfKicker: "Meu Eu",
    profileTitle: "Sua jornada OFF",
    profileKicker: "Perfil",
    moreTitle: "Conheça Mais",
    moreKicker: "OFF",
    behindOff: "Por trás da OFF",
    behindOffCopy: "Por trás da OFF há alguém que também continua se construindo.",
    chatTitle: "Chat OFF",
    chatKicker: "Chat",
    language: "Idioma",
    exit: "Sair",
    articlesCompleted: "Artigos concluídos",
    badges: "Insígnias",
    noArticles: "Quando capítulos forem publicados, aparecerão aqui com dados reais.",
    volume: "Volume",
    more: "Mais",
    mobileLoungeNavigation: "Navegação do Lounge",
    chatWelcome: "Olá, sou seu assistente OFF. Estou aqui para ajudar a organizar ideias, entender o que você sente e transformar isso em clareza prática.",
    chatPending: "Organizando a ideia...",
    chatPlaceholder: "Escreva o que você quer organizar...",
    chatMessage: "Mensagem para o assistente OFF",
    send: "Enviar",
    backToLounge: "Voltar ao Lounge",
  },
} as const;

export function useMobileCopy(initialLanguage?: string | null) {
  const [language, setLanguage] = useState<UiLanguage>(() => normalizeUiLanguage(initialLanguage ?? null));

  useEffect(() => {
    const sync = (value?: string) => setLanguage(value ? normalizeUiLanguage(value) : resolveClientLanguage(initialLanguage));
    sync();
    persistClientLanguage(resolveClientLanguage(initialLanguage), false);
    const listener = (event: Event) => sync((event as CustomEvent<string>).detail);
    const storageListener = () => sync();
    window.addEventListener("off-language-change", listener);
    window.addEventListener("storage", storageListener);
    return () => {
      window.removeEventListener("off-language-change", listener);
      window.removeEventListener("storage", storageListener);
    };
  }, [initialLanguage]);

  return { language, copy: mobileCopy[language] };
}
