import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { getDb } from "@/lib/db";
import { searchOffContent } from "@/lib/off-search";
import { getPersonalMap } from "@/lib/personal-map";
import { normalizeUiLanguage } from "@/lib/ui-i18n";
import { consumeRateLimit } from "@/lib/rate-limit";

const clean = (value: unknown, limit: number) => typeof value === "string" ? value.replace(/<[^>]*>/g, "").trim().slice(0, limit) : "";
const answerCopy = {
  es: { found: "Encontré contenido de OFF que puede ayudarte a seguir esta pregunta sin convertirla en una conclusión sobre ti.", empty: "No encontré una coincidencia exacta todavía. Podemos convertir lo que preguntas en una búsqueda más concreta dentro de OFF.", saved: (title: string, text: string) => `Guardaste este fragmento en “${title}”:\n\n“${text}”\n\nPuede ser un buen lugar para retomar la idea.`, map: (theme: string) => `Con tu permiso, veo que ${theme} aparece con frecuencia reciente en tu mapa. Esto describe actividad voluntaria, no un diagnóstico.` },
  en: { found: "I found OFF content that can help you continue this question without turning it into a conclusion about you.", empty: "I have not found an exact match yet. We can turn your question into a more specific search inside OFF.", saved: (title: string, text: string) => `You saved this fragment in “${title}”:\n\n“${text}”\n\nIt may be a useful place to resume the idea.`, map: (theme: string) => `With your permission, I can see that ${theme} appears frequently in your recent map. This describes voluntary activity, not a diagnosis.` },
  it: { found: "Ho trovato contenuti OFF che possono aiutarti a proseguire questa domanda senza trasformarla in una conclusione su di te.", empty: "Non ho ancora trovato una corrispondenza esatta. Possiamo rendere la tua domanda una ricerca più specifica dentro OFF.", saved: (title: string, text: string) => `Hai salvato questo frammento in “${title}”:\n\n“${text}”\n\nPuò essere un buon punto da cui riprendere l'idea.`, map: (theme: string) => `Con il tuo permesso, vedo che ${theme} ricorre spesso nella tua mappa recente. Descrive attività volontarie, non una diagnosi.` },
  pt: { found: "Encontrei conteúdo da OFF que pode ajudar você a continuar essa pergunta sem transformá-la em uma conclusão sobre si.", empty: "Ainda não encontrei uma correspondência exata. Podemos transformar sua pergunta em uma busca mais específica dentro da OFF.", saved: (title: string, text: string) => `Você salvou este trecho em “${title}”:\n\n“${text}”\n\nPode ser um bom lugar para retomar a ideia.`, map: (theme: string) => `Com sua permissão, vejo que ${theme} aparece com frequência no seu mapa recente. Isso descreve atividade voluntária, não um diagnóstico.` },
};
export async function GET(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); const id = new URL(request.url).searchParams.get("conversationId"); if (id) { const conversation = await getDb().askOffConversation.findFirst({ where: { id, userId: user.id }, include: { messages: { orderBy: { createdAt: "asc" } } } }); return NextResponse.json({ success: Boolean(conversation), conversation }); } const conversations = await getDb().askOffConversation.findMany({ where: { userId: user.id }, select: { id: true, title: true, usePersonalContext: true, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 20 }); return NextResponse.json({ success: true, conversations, personalContextAllowed: user.askOffPersonalContext }); }

export async function POST(request: Request) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); if (!await consumeRateLimit("ask-off", user.id, 20, 60_000)) return NextResponse.json({ success: false, error: "Espera un momento." }, { status: 429 });
  const body = await request.json().catch(() => null) as { message?: unknown; conversationId?: unknown; usePersonalContext?: unknown } | null; const message = clean(body?.message, 1200); if (!message) return NextResponse.json({ success: false }, { status: 400 }); const language = normalizeUiLanguage(user.preferredLanguage); const requestedPersonal = body?.usePersonalContext === true; const usePersonal = requestedPersonal && user.askOffPersonalContext;
  const [sources, highlights, map] = await Promise.all([searchOffContent(message, language), usePersonal ? getDb().articleHighlight.findMany({ where: { userId: user.id }, include: { article: { select: { title: true, slug: true } } }, orderBy: { updatedAt: "desc" }, take: 30 }) : [], usePersonal ? getPersonalMap(user.id, language) : Promise.resolve(null)]);
  const words = message.toLowerCase().split(/\W+/).filter((word) => word.length > 3); const matchingHighlight = highlights.find((item) => words.some((word) => `${item.selectedText} ${item.note ?? ""}`.toLowerCase().includes(word))); const topSources = sources.slice(0, 3); const sourceLines = topSources.map((source) => `• ${source.title}`).join("\n"); const t = answerCopy[language];
  let answer = topSources.length ? `${t.found}\n\n${sourceLines}` : t.empty;
  if (matchingHighlight) answer = t.saved(matchingHighlight.article.title, matchingHighlight.selectedText); else if (usePersonal && map?.signals[0]) answer += `\n\n${t.map(map.signals[0].label)}`;
  const db = getDb(); let conversation = typeof body?.conversationId === "string" ? await db.askOffConversation.findFirst({ where: { id: body.conversationId, userId: user.id } }) : null; if (!conversation) conversation = await db.askOffConversation.create({ data: { userId: user.id, title: message.slice(0, 72), usePersonalContext: usePersonal } });
  const sourceData = [...topSources.map((source) => ({ title: source.title, href: source.href ?? "/lounge" })), ...(matchingHighlight ? [{ title: matchingHighlight.article.title, href: `/off/${matchingHighlight.article.slug}#highlight-${matchingHighlight.id}` }] : [])]; await db.$transaction([db.askOffMessage.create({ data: { conversationId: conversation.id, role: "user", content: message } }), db.askOffMessage.create({ data: { conversationId: conversation.id, role: "assistant", content: answer, sources: sourceData } }), db.askOffConversation.update({ where: { id: conversation.id }, data: { usePersonalContext: usePersonal } })]);
  return NextResponse.json({ success: true, conversationId: conversation.id, message: { id: crypto.randomUUID(), role: "assistant", content: answer, sources: sourceData } });
}

export async function PATCH(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); const body = await request.json().catch(() => null) as { allowPersonal?: unknown } | null; const allow = body?.allowPersonal === true; await getDb().user.update({ where: { id: user.id }, data: { askOffPersonalContext: allow } }); return NextResponse.json({ success: true, allowed: allow }); }
export async function DELETE(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); const body = await request.json().catch(() => null) as { conversationId?: unknown } | null; const result = await getDb().askOffConversation.deleteMany({ where: { id: typeof body?.conversationId === "string" ? body.conversationId : "", userId: user.id } }); return NextResponse.json({ success: result.count === 1 }); }
