"use client";

import { MessageCircleMore, Pin, Sparkles } from "lucide-react";
import { ThreadedComments } from "@/components/ThreadedComments";
import type { UiLanguage } from "@/lib/ui-i18n";

type Conversation = { id: string; question: string; introduction: string | null; themes: string[]; closesAt: string | null; replyCount: number };
const labels = { es: { title: "Conversaciones OFF", closed: "Conversación cerrada", intro: "Preguntas editoriales para nombrar lo que todavía no está resuelto." }, en: { title: "OFF Conversations", closed: "Conversation closed", intro: "Editorial questions for naming what is not resolved yet." }, it: { title: "Conversazioni OFF", closed: "Conversazione chiusa", intro: "Domande editoriali per nominare ciò che non è ancora risolto." }, pt: { title: "Conversas OFF", closed: "Conversa encerrada", intro: "Perguntas editoriais para nomear o que ainda não está resolvido." } };
export function EditorialConversations({ conversations, language }: { conversations: Conversation[]; language: UiLanguage }) { const t = labels[language]; if (!conversations.length) return null; return <section className="off-editorial-conversations"><header><div><p>OFF EDITORIAL</p><h2>{t.title}</h2><span>{t.intro}</span></div><MessageCircleMore /></header><div>{conversations.map((conversation) => { const closed = Boolean(conversation.closesAt && new Date(conversation.closesAt) < new Date()); return <article id={`conversation-${conversation.id}`} key={conversation.id}><div className="off-conversation-copy"><span><Sparkles />{conversation.themes.join(" · ")}</span><h3>{conversation.question}</h3>{conversation.introduction ? <p>{conversation.introduction}</p> : null}{closed ? <em><Pin />{t.closed}</em> : null}</div><ThreadedComments endpoint={`/api/conversations/${conversation.id}/replies`} initialCount={conversation.replyCount} language={language} allowLikes readOnly={closed} likeEndpointPrefix="/api/conversations/replies" compact /></article>; })}</div></section>; }
