"use client";

import { BookMarked, Compass, FileText, Search, Sparkles } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { MapSignal } from "@/lib/personal-map";
import type { UiLanguage } from "@/lib/ui-i18n";

type ArchiveHighlight = { id: string; selectedText: string; note: string | null; updatedAt: string; article: { title: string; slug: string } };
type RitualEntry = { id: string; content: string; updatedAt: string; ritual: { prompt: string } };
const translations = {
  es: { title: "Mi Mapa OFF", subtitle: "Esto es lo que parece estar ocupando tu atención.", explain: "¿Por qué aparece esto?", archive: "Tu archivo", highlights: "Subrayados", notes: "Notas", rituals: "Rituales", conversations: "Conversaciones", search: "Buscar en mi archivo", empty: "Tu mapa tomará forma a medida que leas, guardes ideas y respondas rituales.", signals: "señales", time: "Tu mapa en el tiempo", private: "Privado para ti" },
  en: { title: "My OFF Map", subtitle: "This is what seems to be occupying your attention.", explain: "Why is this here?", archive: "Your archive", highlights: "Highlights", notes: "Notes", rituals: "Rituals", conversations: "Conversations", search: "Search my archive", empty: "Your map will take shape as you read, save ideas and answer rituals.", signals: "signals", time: "Your map over time", private: "Private to you" },
  it: { title: "La mia Mappa OFF", subtitle: "Questo è ciò che sembra occupare la tua attenzione.", explain: "Perché appare?", archive: "Il tuo archivio", highlights: "Sottolineature", notes: "Note", rituals: "Rituali", conversations: "Conversazioni", search: "Cerca nel mio archivio", empty: "La tua mappa prenderà forma leggendo, salvando idee e rispondendo ai rituali.", signals: "segnali", time: "La tua mappa nel tempo", private: "Privato per te" },
  pt: { title: "Meu Mapa OFF", subtitle: "Isto é o que parece estar ocupando sua atenção.", explain: "Por que isso aparece?", archive: "Seu arquivo", highlights: "Destaques", notes: "Notas", rituals: "Rituais", conversations: "Conversas", search: "Buscar no meu arquivo", empty: "Seu mapa ganhará forma conforme você lê, salva ideias e responde aos rituais.", signals: "sinais", time: "Seu mapa ao longo do tempo", private: "Privado para você" },
};

export function PersonalMapExperience({ signals, highlights, rituals, language }: { signals: MapSignal[]; highlights: ArchiveHighlight[]; rituals: RitualEntry[]; language: UiLanguage }) {
  const t = translations[language]; const [selected, setSelected] = useState<MapSignal | null>(signals[0] ?? null); const [tab, setTab] = useState<"highlights" | "notes" | "rituals">("highlights"); const [query, setQuery] = useState("");
  const filteredHighlights = useMemo(() => highlights.filter((item) => `${item.selectedText} ${item.note ?? ""} ${item.article.title}`.toLowerCase().includes(query.toLowerCase())), [highlights, query]);
  const filteredRituals = useMemo(() => rituals.filter((item) => `${item.content} ${item.ritual.prompt}`.toLowerCase().includes(query.toLowerCase())), [rituals, query]);
  const months = useMemo(() => {
    const result = new Map<string, string[]>(); highlights.forEach((item) => { const key = new Intl.DateTimeFormat(language, { month: "long", year: "numeric" }).format(new Date(item.updatedAt)); const themes = signals.filter((signal) => signal.highlights.some((highlight) => highlight.id === item.id)).map((signal) => signal.label); result.set(key, [...new Set([...(result.get(key) ?? []), ...themes])]); }); return [...result.entries()].slice(0, 6);
  }, [highlights, language, signals]);
  return <main className="off-map-shell"><header><p>PERSONAL INTELLIGENCE LAYER</p><h1>{t.title}</h1><span>{t.subtitle}</span><em><Sparkles />{t.private}</em></header>
    <section className="off-map-main"><div className="off-map-constellation" aria-label={t.title}>{signals.length ? signals.slice(0, 10).map((signal, index) => <button className={selected?.theme === signal.theme ? "is-active" : ""} style={{ "--node-size": `${Math.min(128, 64 + signal.count * 7)}px`, "--node-angle": `${index * 37}deg` } as React.CSSProperties} type="button" onClick={() => setSelected(signal)} key={signal.theme}><span>{signal.label}</span><small>{signal.count} {t.signals}</small></button>) : <div className="off-map-empty"><Compass /><p>{t.empty}</p></div>}</div>{selected ? <aside className="off-map-detail"><p>{selected.label}</p><h2>{selected.count} {t.signals}</h2><h3>{t.explain}</h3><ul>{[...new Set(selected.reasons)].slice(0, 8).map((reason) => <li key={reason}>{reason}</li>)}</ul>{selected.articles.map((article) => <Link href={`/off/${article.slug}`} key={article.slug}>{article.title}</Link>)}{selected.highlights.map((highlight) => <Link href={`/off/${highlight.articleSlug}#highlight-${highlight.id}`} key={highlight.id}>“{highlight.text.slice(0, 80)}”</Link>)}{selected.conversations.map((conversation) => <Link href={`/lounge/community#conversation-${conversation.id}`} key={conversation.id}>{t.conversations}: {conversation.question}</Link>)}</aside> : null}</section>
    <section className="off-map-timeline"><h2>{t.time}</h2>{months.length ? months.map(([month, themes]) => <article key={month}><strong>{month}</strong><span>{themes.join(" · ") || "Lecturas y notas"}</span></article>) : <p>{t.empty}</p>}</section>
    <section className="off-personal-archive"><header><div><p>PRIVATE MEMORY</p><h2>{t.archive}</h2></div><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} /></label></header><nav><button className={tab === "highlights" ? "is-active" : ""} onClick={() => setTab("highlights")}><BookMarked />{t.highlights}</button><button className={tab === "notes" ? "is-active" : ""} onClick={() => setTab("notes")}><FileText />{t.notes}</button><button className={tab === "rituals" ? "is-active" : ""} onClick={() => setTab("rituals")}><Sparkles />{t.rituals}</button></nav><div>{tab !== "rituals" ? filteredHighlights.filter((item) => tab === "highlights" || item.note).map((item) => <Link className="off-archive-card" href={`/off/${item.article.slug}#highlight-${item.id}`} key={item.id}><blockquote>“{item.selectedText}”</blockquote>{item.note ? <p>{item.note}</p> : null}<span>{item.article.title}</span></Link>) : filteredRituals.map((item) => <article className="off-archive-card" key={item.id}><strong>{item.ritual.prompt}</strong><p>{item.content}</p><time>{new Intl.DateTimeFormat(language, { dateStyle: "medium" }).format(new Date(item.updatedAt))}</time></article>)}</div></section>
  </main>;
}
