import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { memberOffId } from "@/lib/community";
import { getDb } from "@/lib/db";
import { consumeRateLimit } from "@/lib/rate-limit";

const clean = (value: unknown) => typeof value === "string" ? value.replace(/<[^>]*>/g, "").trim().slice(0, 1000) : "";
const shape = (item: any, userId: string, admin: boolean) => ({ id: item.id, parentId: item.parentId, content: item.content, createdAt: item.createdAt.toISOString(), user: { id: item.user.id, name: item.user.name, offId: memberOffId(item.user.memberProfile?.memberNumber) }, likeCount: item._count.likes, likedByViewer: item.likes.length > 0, canDelete: admin || item.userId === userId, replyCount: item._count.replies, replies: item.replies?.map((reply: any) => shape({ ...reply, replies: [] }, userId, admin)) ?? [], featured: item.featured, pinned: item.pinned });

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); const { id } = await params; const url = new URL(request.url); const parentId = url.searchParams.get("parentId"); const offset = Number(url.searchParams.get("offset") ?? 0) || 0;
  const replies = await getDb().editorialConversationReply.findMany({ where: { conversationId: id, parentId: parentId || null, status: "PUBLISHED" }, include: { user: { select: { id: true, name: true, memberProfile: { select: { memberNumber: true } } } }, likes: { where: { userId: user.id } }, _count: { select: { likes: true, replies: true } }, replies: { where: { status: "PUBLISHED" }, take: parentId ? 0 : 3, orderBy: { createdAt: "asc" }, include: { user: { select: { id: true, name: true, memberProfile: { select: { memberNumber: true } } } }, likes: { where: { userId: user.id } }, _count: { select: { likes: true, replies: true } } } } }, orderBy: [{ pinned: "desc" }, { featured: "desc" }, { createdAt: parentId ? "asc" : "desc" }], skip: offset, take: parentId ? 4 : 20 });
  return NextResponse.json({ success: true, comments: replies.map((item) => shape(item, user.id, user.role === "ADMIN")) });
}

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); if (!await consumeRateLimit("editorial-reply", user.id, 10, 60_000)) return NextResponse.json({ success: false, error: "Espera un momento." }, { status: 429 }); const { id } = await params; const body = await request.json().catch(() => null) as { content?: unknown; parentId?: unknown } | null; const content = clean(body?.content);
  const db = getDb(); const conversation = await db.editorialConversation.findFirst({ where: { id, status: "published" }, select: { closesAt: true } }); if (!conversation) return NextResponse.json({ success: false }, { status: 404 }); if (conversation.closesAt && conversation.closesAt < new Date()) return NextResponse.json({ success: false, error: "Conversación cerrada." }, { status: 409 });
  const requested = typeof body?.parentId === "string" ? body.parentId : null; const parent = requested ? await db.editorialConversationReply.findFirst({ where: { id: requested, conversationId: id }, select: { id: true, parentId: true, userId: true } }) : null; if (!content || (requested && !parent)) return NextResponse.json({ success: false }, { status: 400 }); const parentId = parent?.parentId ?? parent?.id ?? null;
  const reply = await db.editorialConversationReply.create({ data: { conversationId: id, userId: user.id, parentId, content }, include: { user: { select: { id: true, name: true, memberProfile: { select: { memberNumber: true } } } }, likes: true, _count: { select: { likes: true, replies: true } } } }); if (parent && parent.userId !== user.id) await db.notification.create({ data: { userId: parent.userId, type: "EDITORIAL_CONVERSATION", title: "Nueva respuesta", message: `${user.name} respondió en una Conversación OFF.`, href: `/lounge/community#conversation-${id}` } });
  return NextResponse.json({ success: true, comment: shape({ ...reply, replies: [] }, user.id, user.role === "ADMIN") });
}

export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ success: false }, { status: 401 }); const { id } = await params; const body = await request.json().catch(() => null) as { commentId?: string } | null; const reply = await getDb().editorialConversationReply.findFirst({ where: { id: body?.commentId, conversationId: id }, select: { id: true, userId: true } }); if (!reply || (user.role !== "ADMIN" && reply.userId !== user.id)) return NextResponse.json({ success: false }, { status: 403 }); await getDb().editorialConversationReply.delete({ where: { id: reply.id } }); return NextResponse.json({ success: true }); }
